name: web-ide

on:
  pull_request_target: 
    types: [opened, synchronize]

jobs:
  add-link:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Web IDE Pull Request Link
        id: try-in-web-ide-testing
        uses: dkwon17/try-in-web-ide@pull_request_target
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Defaults
          # add_comment: true
          # add_status: true
          # web_ide-instance: https://workspaces.openshift.com
          # comment_badge: https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940
